package me.sheepyang.onlylive.entity.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import me.sheepyang.onlylive.entity.JoinOwnerToGoods;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_OWNER_TO_GOODS".
*/
public class JoinOwnerToGoodsDao extends AbstractDao<JoinOwnerToGoods, Long> {

    public static final String TABLENAME = "JOIN_OWNER_TO_GOODS";

    /**
     * Properties of entity JoinOwnerToGoods.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property OwnerId = new Property(1, long.class, "ownerId", false, "OWNER_ID");
        public final static Property GoodsId = new Property(2, long.class, "goodsId", false, "GOODS_ID");
    };


    public JoinOwnerToGoodsDao(DaoConfig config) {
        super(config);
    }
    
    public JoinOwnerToGoodsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_OWNER_TO_GOODS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"OWNER_ID\" INTEGER NOT NULL ," + // 1: ownerId
                "\"GOODS_ID\" INTEGER NOT NULL );"); // 2: goodsId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_OWNER_TO_GOODS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinOwnerToGoods entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getOwnerId());
        stmt.bindLong(3, entity.getGoodsId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinOwnerToGoods entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getOwnerId());
        stmt.bindLong(3, entity.getGoodsId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public JoinOwnerToGoods readEntity(Cursor cursor, int offset) {
        JoinOwnerToGoods entity = new JoinOwnerToGoods( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // ownerId
            cursor.getLong(offset + 2) // goodsId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinOwnerToGoods entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setOwnerId(cursor.getLong(offset + 1));
        entity.setGoodsId(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinOwnerToGoods entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinOwnerToGoods entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
